[features]
seeds = false
skip-lint = false
[programs.devnet]
yours_nft = "AofVbSrzmpWsg4vym4Gq3uCzKqtRjZLTMo8FTvycR8MZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/xione/.config/solana/id.json"

[scripts]
MintSellNFT = "yarn run ts-node ./app/main.ts"
test_mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mint.test.ts"
test_sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sell.test.ts"
